config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :lego_sets do
    collection do
      get 'cards'
    end

    member do
      get 'card'
    end
  end

  namespace :rebrickable do
    get 'search', to: 'api#search'
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lego_set.rb
class LegoSet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  has_many :lego_sets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/lego_sets_controller.rb
require 'rest-client'

class LegoSetsController < ApplicationController
  
  def index 
    @lego_sets = current_user.lego_sets.all
  end

  def cards
    @lego_sets = current_user.lego_sets.all
  end

  def show
    @lego_set = current_user.lego_sets.find(params[:id])
  end

  def card
    @lego_set = current_user.lego_sets.find(params[:id])
  end
  
  def new
    @lego_set = current_user.lego_sets.build
  end

  def create
    @lego_set = current_user.lego_sets.build(lego_set_params)
    
    @lego_set.instructions_url = instructions_url(@lego_set.set_id)

    @lego_set.save
    redirect_to @lego_set
  end

  def destroy
    @lego_set = current_user.lego_sets.find(params[:id])
    @lego_set.destroy

    redirect_to lego_sets_path
  end

  private
    def lego_set_params
      params.require(:lego_set).permit(:set_id, :name, :thumbnail_url)
    end

    def instructions_url(set_id)
      base_url = 'http://lego.brickinstructions.com'
      clean_set_id = set_id.split('_')[0]

      search_url = "#{base_url}/search/general/send"

      # We expect a 302 here
      begin
        response = RestClient.post search_url, { set: clean_set_id.to_i }
      rescue RestClient::ExceptionWithResponse => err
        instructions_location = err.response.headers[:location]
      end

      "#{base_url}#{instructions_location}"
    end
end

app/controllers/rebrickable/api_controller.rb
require 'rest-client'
require 'json'

module Rebrickable
  class ApiController < ApplicationController
    @@baseUri = 'https://rebrickable.com/api/v3'

    def search
      render json: doSearch(params['search'])
    end

    private
      def doSearch(term, limit=10)
        # Perform the search through the Rebrickable API
        searchUrl = "#{@@baseUri}/lego/sets/?search=#{term}&page_size=#{limit}"
        resultJson = RestClient.get searchUrl, { authorization: authorization } 
        results = JSON.parse(resultJson)

        # Extract and return just the results collection
        results['results']
      end

      def authorization
        "key #{ENV['REBRICKABLE_API_KEY']}"
      end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @latest_sets = current_user.lego_sets.order('updated_at DESC').limit(3).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rebrickable_helper.rb
module RebrickableHelper
end

app/helpers/sets_helper.rb
module SetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>LEGO</title>
  <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
    <%= link_to 'Oh My Lego', root_url, { class: 'navbar-brand' } %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'All Sets', lego_sets_path, { class: 'nav-link' } %>
          </li>
          <li class="nav-item">
            <%= link_to  "Add Set", new_lego_set_path, { class: 'nav-link'} %>
          </li>
        </ul>



        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.email %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'dropdown-item' %>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %>
              </div>
            </li>

            <% else %>
              <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %>
              </li>
              <li class="nav-item"></li>
              <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
                </li>
                <% end %>
        </ul>
      </div>
  </nav>
  <% if notice %>
    <div class="alert alert-banner alert-primary" role="alert">
      <%= notice %>
    </div>
    <% end %>

      <% if alert %>
        <div class="alert alert-banner alert-danger" role="alert">
          <%= alert %>
        </div>
        <% end %>

          <%= yield %>
</body>

</html>

app/views/lego_sets/_card.html.erb
<div class="print-card">
    <h1 class="print-card-name">
        <%=lego_set.name%>
        <br>
        <small>
            <%=lego_set.set_id%>
        </small>
      </h1>
      <div class="print-card-images">
        <div class="print-card-thumbnail">
            <img src="<%=lego_set.thumbnail_url%>">
        </div>
        <div class="print-card-qr">
            <img src="//api.qrserver.com/v1/create-qr-code/?data=<%= URI.encode(lego_set.instructions_url)%>&size=300x300">
        </div>
      </div>
</div>

app/views/lego_sets/_form.html.erb
<%= form_with model: @lego_set, local: true, :class => 'form' do |form| %>

  <%= react_component 'LegoSetSearch', { data: @records } %>

  <%= form.submit 'Save', :class => 'btn btn-primary' %>

<% end %>

app/views/lego_sets/card.html.erb
<%= render :partial => "card", :object => @lego_set %>

app/views/lego_sets/cards.html.erb
<%= render :partial => "card", :collection => @lego_sets, :as => :lego_set %>

app/views/lego_sets/index.html.erb
<div class="container">
    <h2>Lego Catalog</h2>
    <div class="row">
      <% @lego_sets.each do |set| %>
  
        <div class="card card-album">
          <a href="<%= url_for lego_set_path(set.id)%>">
            <img src="<%= set.thumbnail_url%>"
            style="width:100%; display: block;">
          </a>
          <p class="card-text">
            <%= set.name %>
          </p>
        </div>
  
        <% end %>
    </div>
  
  </div>

app/views/lego_sets/new.html.erb
<div class="container">
  <h1>Add Lego Set</h1>

  <div class="row">
    <div class="col">

      <%= render 'form' %>
    </div>

  </div>
</div>

app/views/lego_sets/show.html.erb
<div class="container">
  <h1>
      <%= @lego_set.name%>
      <small>
          <%= @lego_set.set_id%>
      </small>
  </h1>

  <div class="row mb-3">
    <div class="col">
      <a href="<%= @lego_set.instructions_url %>" target="_blank" class="btn btn-primary">Build  Instructions</a>
      <%= link_to 'All Sets', lego_sets_path,  class: 'btn btn-light' %>
      <%= link_to 'Add Another', new_lego_set_path,  class: 'btn btn-light' %>
      <%= link_to 'Delete', lego_set_path(@lego_set),  class: 'btn btn-outline-danger',
          method: :delete,
          data: { confirm: 'Are you sure you want to remove this set?' } %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <img src="<%= @lego_set.thumbnail_url %>">
    </div>
  </div>

</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">


    <%= image_tag "legoman.gif", width: 65, class: 'lego-man' %>
      <h1 class="display-4" style="margin-left: 80px">Oh My Lego!</h1>
      <p class="lead" style="margin-left: 80px">
        A place to catalog lego sets in your collection, and keep track of building instructions.
      </p>
      <hr class="my-4">
      <p>
        Use the options here to add sets to your collection, or create reference cards.
      </p>
      <p class="lead">
        <%= link_to  "Add Set", new_lego_set_path, { class: 'btn btn-primary btn-lg'} %>
      </p>
  </div>
</div>

<div class="container">
  <h2>Recently Updated</h2>
  <div class="row">

    <% if @latest_sets.empty? %>
      <div class="col alert alert-warning">
        You haven't added any sets to your library yet!
      </div>
    <% end %>

    <% @latest_sets.each do |set| %>

      <div class="card card-album">
        <a href="<%= url_for lego_set_path(set.id)%>">
          <img src="<%= set.thumbnail_url%>"
          style="width: 100%; display: block;">
        </a>
        <p class="card-text">
          <%= set.name %>
        </p>
      </div>

      <% end %>
  </div>

</div>